# Schema for the configuration files of the blockscontent module.
blockscontent.settings:
  type: config_object
  label: 'blockscontent settings'
  mapping:
    example:
      type: string
      label: 'Example'
